- hosts: centos
  roles:
    - ypsman.resolv
    - juju4.ipv6
    - ruzickap.proxy_settings
  tasks:
    - name: Configure UTF8
      shell: export LANG=en_US.utf8
    - name: Copie KEY
      copy:
        src: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        owner: root
        group: root
        mode: 0644
    - name: Install EPEL-7
      yum: name=epel-release state=latest
    - name: Update
      shell: yum update -y